apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'services'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names: [seblaz]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: '(postgres-service)'
            action: drop
