apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-config
data:
  prometheus.yaml: |
    datasources:
      - name: Prometheus
        url: http://prometheus-service:9090
        type: prometheus
