apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_SERVER_HTTP_PORT: "3000"
  GF_DATABASE_TYPE: "postgres"
  GF_PATHS_DATA: "/var/lib/grafana"
  GF_PATHS_PROVISIONING: "/etc/grafana/provisioning"
