apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    run: grafana-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: grafana-port
  selector:
    app: grafana
