apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    run: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-port
  selector:
    app: postgres-database
